backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "Projects"
    label: "Projects"
    folder: "src/pages/projects"
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "project"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: "Subheading", name: "subheading", widget: "string"}
          - {label: "Mission", name: "mission", widget: "object", fields: [{label: "Title", name: "title", widget: "string"}, {label: "Statement", name: "statement", widget: "text"}]}
          - {label: "Medical Conditions", name: "medicalConditions", widget: "object", fields: [{label: "Heading", name: "heading", widget: "string"}, {label: "Diseases", name: "diseases", widget: "list", fields: [{label: "Name", name: "name", widget: "string"}]}]}
          - {label: "Projects Heading", name: "projects", widget: "string"}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/bylaws/index.md"
        label: "Bylaws"
        name: "bylaws"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "bylaws-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/education/index.md"
        label: "Education"
        name: "education"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "education-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Intro", name: "intro", widget: "object", fields: [{label: "Heading", name: "heading", widget: "string"}, {label: "Content", name: "text", widget: "text"}]}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/volunteer/index.md"
        label: "Volunteer Page"
        name: "volunteer"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "volunteer-page"}
          - {label: "Header Image", name: "image", widget: "image"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Intro", name: "intro", widget: "object", fields: [{label: "Heading", name: "heading", widget: "string"}, {label: "Content", name: "text", widget: "text"}]}
          - {label: "Content Image", name: "mainImage", widget: "image"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Volunteer Positions", name: "volunteerList", widget: "object", fields: [{label: "Heading", name: "heading", widget: "string"}, {label: "Positions", name: "positions", widget: "list", fields: [{label: "Name", name: "name", widget: "string"}, {label: "Description", name: "description", widget: "string"}]}]}
